# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/signed_adder/signed_adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signed_adder || ORIG_REF_NAME==signed_adder} -quiet] -quiet

# Block Designs: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/adder_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd || ORIG_REF_NAME==adder_bd} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_zynq_ultra_ps_e_0_0/adder_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==adder_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_axi_gpio_0_0/adder_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_axi_gpio_0_0 || ORIG_REF_NAME==adder_bd_axi_gpio_0_0} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_axi_gpio_0_1/adder_bd_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_axi_gpio_0_1 || ORIG_REF_NAME==adder_bd_axi_gpio_0_1} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_axi_gpio_0_2/adder_bd_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_axi_gpio_0_2 || ORIG_REF_NAME==adder_bd_axi_gpio_0_2} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_xbar_0/adder_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_xbar_0 || ORIG_REF_NAME==adder_bd_xbar_0} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_auto_ds_0/adder_bd_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_auto_ds_0 || ORIG_REF_NAME==adder_bd_auto_ds_0} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_auto_pc_0/adder_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_auto_pc_0 || ORIG_REF_NAME==adder_bd_auto_pc_0} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_ps8_0_axi_periph_0/adder_bd_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_ps8_0_axi_periph_0 || ORIG_REF_NAME==adder_bd_ps8_0_axi_periph_0} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_rst_ps8_0_100M_0/adder_bd_rst_ps8_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_rst_ps8_0_100M_0 || ORIG_REF_NAME==adder_bd_rst_ps8_0_100M_0} -quiet] -quiet

# IP: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/ip/adder_bd_Adder_0_0/adder_bd_Adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder_bd_Adder_0_0 || ORIG_REF_NAME==adder_bd_Adder_0_0} -quiet] -quiet

# IP: ip/signed_adder/signed_adder.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signed_adder || ORIG_REF_NAME==signed_adder} -quiet] -quiet

# XDC: /home/yuhaoliu/Projects/Verilog/AXI-GPIO-Ultra96V2/src/bd/adder_bd/adder_bd_ooc.xdc
