# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-GPIO/src/bd/adder_bd/ip/adder_bd_Adder_0_0/adder_bd_Adder_0_0.xci
# IP: The module: 'adder_bd_Adder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-GPIO/AXI_GPIO.srcs/sources_1/ip/signed_adder/signed_adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signed_adder || ORIG_REF_NAME==signed_adder} -quiet] -quiet

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-GPIO/src/bd/adder_bd/ip/adder_bd_Adder_0_0/adder_bd_Adder_0_0.xci
# IP: The module: 'adder_bd_Adder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/yuhao_liu/Projects/Hardware/FPGA/Ultra96V2/AXI-GPIO/AXI_GPIO.srcs/sources_1/ip/signed_adder/signed_adder.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==signed_adder || ORIG_REF_NAME==signed_adder} -quiet] -quiet
